version: '3.7'

services:
  web:
    build: ./
    command: /bin/sh -c "python manage.py migrate; gunicorn botify.wsgi:application --bind 0.0.0.0:8000"
    ports: 
      - 8000:8000
    env_file:
      - ./.docker/.env
    volumes:
      - database:/app/home/web/database
  nginx:
    image: nginx:alpine
    ports: 
      - 8080:80
    environment:
      NGINX_CONFIG: |
        upstream botify {
          server web:8000;
        }

        server {
          listen 80 http2;
          location / {
            proxy_pass http://botify;
              proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
              proxy_set_header Host $$host;
              proxy_redirect off;
          }
        }
    command: /bin/sh -c "echo \"$$NGINX_CONFIG\" > /etc/nginx/conf.d/default.conf; nginx -g \"daemon off;\""

volumes:
  database: